# Generated by Django 2.1.7 on 2019-05-28 02:50

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('active', models.BooleanField(default=False)),
                ('message', models.CharField(max_length=3000)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message='Only alphanumeric characters and - are allowed.', regex='^[A-Za-z \\-]*$')])),
                ('model', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message='Only letters, digits and - are allowed.', regex='^[a-zA-Z0-9]*$')])),
                ('price', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3000000)])),
                ('production_year', models.IntegerField(validators=[django.core.validators.MinValueValidator(1800), django.core.validators.MaxValueValidator(2021)])),
                ('city', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message='Only alphanumeric characters and - are allowed.', regex='^[A-Za-z \\-]*$')])),
                ('street', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message='Only alphanumeric characters and - are allowed.', regex='^[A-Za-z \\-]*$')])),
                ('power', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2021)])),
                ('capacity', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(8)])),
                ('drive_train', models.CharField(choices=[('RWD', 'Rear Wheel Drive'), ('FWD', 'Front Wheel Drive'), ('AWD', 'All Wheel Drive')], max_length=4)),
                ('description', models.CharField(max_length=10000)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='reservation',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car', to='vehicles_sharing.Vehicle'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reservation',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL),
        ),
    ]
