# Generated by Django 2.1.7 on 2019-03-31 14:37

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('active', models.BooleanField(default=False)),
                ('message', models.CharField(max_length=3000)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('login', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=50)),
                ('mail', models.CharField(max_length=100, validators=[django.core.validators.EmailValidator])),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('price', models.IntegerField(default=0)),
                ('production_year', models.CharField(max_length=4, validators=[django.core.validators.RegexValidator(code='nomatch', message='Year must be 4 digits long', regex='^.{4}$')])),
                ('city', models.CharField(max_length=50)),
                ('street', models.CharField(max_length=50)),
                ('power', models.IntegerField(null=True)),
                ('capacity', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(8)])),
                ('drive_train', models.CharField(choices=[('AWD', 'All Wheel Drive'), ('RWD', 'Rear Wheel Drive'), ('FWD', 'Front Wheel Drive')], max_length=4)),
                ('description', models.CharField(max_length=10000)),
                ('owner_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicles_sharing.User')),
            ],
        ),
        migrations.AddField(
            model_name='reservation',
            name='car_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id3', to='vehicles_sharing.Vehicle'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='client_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id2', to='vehicles_sharing.User'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='owner_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id1', to='vehicles_sharing.User'),
        ),
    ]
