# Generated by Django 2.1.7 on 2019-03-31 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles_sharing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='car_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_id', to='vehicles_sharing.Vehicle'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='client_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_id', to='vehicles_sharing.User'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='owner_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner_id', to='vehicles_sharing.User'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='drive_train',
            field=models.CharField(choices=[('FWD', 'Front Wheel Drive'), ('RWD', 'Rear Wheel Drive'), ('AWD', 'All Wheel Drive')], max_length=4),
        ),
    ]
