# Generated by Django 2.1.7 on 2019-04-25 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles_sharing', '0002_auto_20190424_0744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='drive_train',
            field=models.CharField(choices=[('AWD', 'All Wheel Drive'), ('RWD', 'Rear Wheel Drive'), ('FWD', 'Front Wheel Drive')], max_length=4),
        ),
    ]
