# Generated by Django 2.2.3 on 2019-07-02 20:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles_sharing', '0002_auto_20190702_1952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='car',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photo', to='vehicles_sharing.Vehicle'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='drive_train',
            field=models.CharField(choices=[('FWD', 'Front Wheel Drive'), ('AWD', 'All Wheel Drive'), ('RWD', 'Rear Wheel Drive')], max_length=4),
        ),
    ]
