# Generated by Django 2.2.1 on 2019-07-22 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles_sharing', '0002_auto_20190601_1727'),
        ('vehicles_sharing', '0003_auto_20190702_2059'),
    ]

    operations = [
    ]
