# Generated by Django 2.1.7 on 2019-04-27 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles_sharing', '0003_auto_20190425_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='drive_train',
            field=models.CharField(choices=[('AWD', 'All Wheel Drive'), ('FWD', 'Front Wheel Drive'), ('RWD', 'Rear Wheel Drive')], max_length=4),
        ),
    ]
