# Generated by Django 2.2.3 on 2019-07-22 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles_sharing', '0002_auto_20190601_1727'),
        ('vehicles_sharing', '0004_auto_20190711_1641'),
    ]

    operations = [
    ]
