# Generated by Django 2.2.1 on 2019-07-22 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles_sharing', '0004_merge_20190722_1600'),
        ('vehicles_sharing', '0004_auto_20190711_1641'),
    ]

    operations = [
    ]
