# Generated by Django 2.2.1 on 2019-07-23 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles_sharing', '0005_merge_20190722_1907'),
        ('vehicles_sharing', '0005_merge_20190723_0017'),
    ]

    operations = [
    ]
