# Generated by Django 2.2 on 2019-04-07 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles_sharing', '0006_auto_20190407_1301'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='owner_id',
        ),
        migrations.DeleteModel(
            name='Reservation',
        ),
        migrations.DeleteModel(
            name='Vehicle',
        ),
    ]
