# Generated by Django 2.2 on 2019-04-09 10:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles_sharing', '0008_reservation_vehicle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='drive_train',
            field=models.CharField(choices=[('RWD', 'Rear Wheel Drive'), ('AWD', 'All Wheel Drive'), ('FWD', 'Front Wheel Drive')], max_length=4),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='power',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2021)]),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='production_year',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1800), django.core.validators.MaxValueValidator(10000)]),
        ),
    ]
