# Generated by Django 2.1.7 on 2019-04-14 21:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles_sharing', '0009_auto_20190409_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='brand',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message='Only alphanumeric characters and - are allowed.', regex='^[A-Za-z \\-]*$')]),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='city',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message='Only alphanumeric characters and - are allowed.', regex='^[A-Za-z \\-]*$')]),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='drive_train',
            field=models.CharField(choices=[('RWD', 'Rear Wheel Drive'), ('FWD', 'Front Wheel Drive'), ('AWD', 'All Wheel Drive')], max_length=4),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='model',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message='Only letters, digits and - are allowed.', regex='^[a-zA-Z0-9]*$')]),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='price',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3000000)]),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='production_year',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1800), django.core.validators.MaxValueValidator(2021)]),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='street',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message='Only alphanumeric characters and - are allowed.', regex='^[A-Za-z \\-]*$')]),
        ),
    ]
